/*
 * Port_cfg.h
 *
 *  Created on: Mar 10, 2022
 *      Author: WINDOWS
 */

#ifndef __PORT_CFG_H__
#define __PORT_CFG_H__

#define PORT_u8PIN_0_INIT_CFG       PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_1_INIT_CFG       PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_2_INIT_CFG       PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_3_INIT_CFG       PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_4_INIT_CFG       PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_5_INIT_CFG       PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_6_INIT_CFG       PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_7_INIT_CFG       PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_8_INIT_CFG       PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_9_INIT_CFG       PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_10_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_11_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_12_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_13_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_14_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_15_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_16_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_17_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_18_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_19_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_20_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_21_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_22_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_23_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_24_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_25_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_26_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_27_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_28_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_29_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_30_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE
#define PORT_u8PIN_31_INIT_CFG      PORT_u8INPUT_HIGHIMPEDANCE

#endif
